sudo: required
services:
- docker
language: python
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: ZRaN2hiCSBXW2G3J5lt2tQVLGEK/DeEKRuH9Fmi5SjTqN6cYzZVD56pD8Ak+LctuFyy3fKPyc2uFDvJDuSlAsjla3H3J4SbfyVsI3gRAwXMD2Ue2ANfZJ/xJIbvv+Zu7REqu+BkqShOtdmbjqWLXy6JMA/3jRVEVIJ/JpX8PE7wwCVVhSMx01odfQYS4wgxv8uM7FVY5Ttc8BaZW/Gv5DF5syGQQwkEA5V3p/0DUMymQcrGBnTFkMgJY8f1K13GXKIR+vT+co+C1fYxZW03ua0frdo4xbeLNRYKKdo+9Fofmfg0+agWTh4WKYFKPeubN6xvAIYZKOdDruRHv/Dc8XxVzcKdEH1Ozhpcz456q/plR3vWNX6wcjTXp6UdNxG16WBT0UkPO4pHLG5zZfN0a6irleX0aJdBo20XOUmzqOKtbaP4RUju5t6vcWB415UqQPtC1x4nPYRK9lIihrkwMomAjQ9/IYtLdq9rh0Dj2z3VlZmK5BB8Mbl+Og1AARU2xbqri7tohb3o5OA8hPmj9lDmY6xKaA6Lsp/55yy4VEUPQyLVE6QEbtI69zvCWTtnMLkeLUy08g0FYjZdD+1dzAxOL1iDKs3bJMFiMriwbIdlTRLFWdzjucRmBCC/33roivIWCahiPrgjY6GfJ3OrBUwh/gD/DAjnxCj8PDX44Vwc=
  - secure: AmRK1NHRxbN/ys9LmDcE/UwhKH17baGovSKt4SdZ6ahZQT8zIwzMm46qHFBHEjgxCG5LHemUK1NW3pY/Ty0UqjO7RZW6gpiMJgG40TAVSzxa/nQE4TlQadVEPqj353+71LakCC5i90pnImigjCX/UjeaHSCARPww49Rx35+3xgYo+lfh9yNOvyKMPorHlsV52P2/FXz07q+Gqg9jFC+MrDBuwRVOd2fM8kC6K/CxDLSt65E2T5SihjBfXrS5R5WSlHyJrGaKob/ua8I3Da7LMOCFksuax9ZdVobfsZD85ebxr8RSugl+aFXActwtLYgEwEcvMJVaorzk9efBkkMX/u9UlE+NK4p6ptMyi1Uc+G2eVg+YKzBAhdBxzj5ivHOZ7Tl3MQNSASRprAT5GXHLrdTjd1yiX2sN4T9blniG7b7QCC0R3VG8WB2S4dgfYVjGjb2SKabaNDh7fuvNS7eLH7oVReH4nXfj0WO6Up770UdJZKRI2qi8+kB5j8rC6zdchIZPqAE6J3Hnd8wr0FpSZvyrX56OY7PJ2jferY5+yrPiXuiwcNDr+jyUHvRkSuwrMBpPyTbFeZXTiyHrxhdG5kq7rjzCnwfGMwL90zwR6MdeKpJQYtcgQU/M0CEszqLqL4t4SCDb0czctnzbslW26syz5+D1fHFOBcc8u0j6pLw=
  - secure: M19SJicoiaFC3Oj0484EPozlGboH+XudhPcdyxn/W0v+LLlYzR8cy1f1U3mk7fgXGCGTgxlT/iesLvMssfieCJ6qg6E9CY8Vw42+GbKJWxAaQ9qNd9Irr3T1UFgi1vK15+fLTB2qlrpXyRALCUJsc8vUCBtBJ8BH2vDeF1fDEoktbovPJb5NP9zZwyvigCSUZoqngppk/KcL0C/v66vAAt2Q9ZsYLgGN+QpzWoojR1w3JDITWdcTPJ+avtv+EnpgR1ARDv4fH5AS3spdAJCo+AguoCMl/OViVuTuWtI+6/bCJjwX+jg3xruTT0WKI7jCMamiekQkuGl5hZ4DUSR9cUZsmq9UpxKK5QV6vKLGz9lbXE7nHR8E8X4W/+rnVS+yNsnDI9e7MpnB/WYPnsxB0gvoInsStfaF/FvrbC4PFZD1FEgfWxs9owNLKiVGlieelHgRNiSErTj7TFKkeevtnaUzS0V6uPO07vUaWvev6v9XkC3uS/k4Ch/c3XlLRvMdaZvBybwPavD6+jXQ7BhgDH4KJYsKQUpV97XHoJf/0ZWu3xAxuFaqR3WYsSfyIFD0cuFFG85iVfYY5XJTbvgczztu9tAUiU/8UuIIzB8Gwuh8PpufXmbTk2/p+gz/1tJeX/c+NTgH0Xe+TCpKGeDU4bBqLlwGus83kKrEXnYFJ8g=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
    - export REPO=cangr/mvsd-mongo-sync
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
