sudo: required
services:
- docker
language: python
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: tlCL8YRV7+ihMFqeQZVwxxC47ITosiqCvUhYEgO2GuDxJT6SYl+pOdN3QxUuFKBi3GT2wTIUCdbW3YC7qCvgi2rpPUfyp/DAlHdeK7mZj7ymSIryK2YzgIq7EgVghRCx0A1SSgkb/QNz1rba/PBleZJuLWd4jqCSRP3qbiUqYDWSiZ73r0nNf6v0NvNzoDKOEerWPU6/jCxnKeWfWHFGVh6XgR0HQkj184GJs/3HT13hXORrwDVXi1OMTKq02TGNNRkNfwAbEXjTfOr47pOkayHkOlWPqlUoObO57u0FVXo1aNWhM4l70WPSC1x69If7FeAbaC7AgxHDmqFhEaOXXij6mGehwzCJnUoXAEVFm6cMoyZwCEnUrPz94gz1Bk8IZm7T+60x/8+ekhXbfBH7wUUZw4l+kA86A0z6y9P6iQmveUIuaa/Cu0XEqdVXs4JWLlTT1ykABpvQRp3Zzh1PvPvWwk1lW3obaEJpw+HwGbin/o2beYEN9sR1dXWIvetrzhodKlSJoGzNUkri8cHX9SG+LdtdArfHmYj0+gTWPKpWyvkn/IQGz70UJ/jS4EVxK0oCy95QH4hLA1OAzT+OJGqxekMtV7Ptm2L+UhaFTPNsEEfGL/2LIJAczPJNsAVbuevLGCb9BeIB2/z969qhHbB7tjHc6CHElgGt4hDNLBc=
  - secure: TMkCaIXg3UYu73UFKZlMd7puqMMbUku0d5PzqNysLBcG6DY55PRrbaqdT0bm1jJ8ZwaWEJpjgw7xkvZRaYmFF9QGRL0PMQdZzrre+FKqjOins0lm7SVE4tdtxIdyvXZqJwfrutOu9rGXuJa+moYrhvZlhFml7fguzPa6ndAp4mxkRTfZZ5sIcMIkWWfaYH65fJTHSyC3pQSkVYoAWU+yqG2qYEnXqG2QUEhiAigu9nvT4CjcxYG0/IRHeXnO7knn/pMVP/t+ai8nAI1Dnd7zBMPse+xA2bYsshAqJwyCTHBSXWVt9kTTqOjndCUi5NGUMtOHux/3ZTw54SvvV6jHehl4w1WKhktxB7Y1Q4lfu+V1yLYUuvVZmqAs/qiKtNxkzRAH8Onik2eQ24MtzDdEBKw691XEPnD+BzNJsxnwj1C2xu4fb8wUwXzdIoJ62vnh3KqGB5h1RwCToLlZutBY3xyY0JLBxSs3E/62yFWs+nzZhhgPoMYSFKGoiPP7c/FqNA8M5nhMAkfTlJgVzCkvhh9mtEYpixuKOtYpaGnmCXf8vN669Gf08X7DIFD3mrcLHzrZNheKLIIRELAZdkEV2cyBnwqjvTi92kRenL48k0KewW7LphDFWubpOv49PqJGKboyY+RJ+t8A0PvXECH0z0sFlN/eNLTnKKt1tqXa9O0=
  - secure: bvXw1l+vHxUZu9PG5+x9Ba6O8l5AE++PRjtZk7fOxq9dV0PIFmCt38T7tmR0re/dYagdoVuYI5F7CUpJ1rhn56RyIqHy1b2rx72dflRFotxtZey0t1akynFRlPPxRqK11vHGNqeQqJZFlHT+8E79V5xnrjPCCt0rD0s/GSNj1vT0RhuB7i5Jxqdbz0bplRu0LzaT258qkjwazJYYbV+rv7aOxo7CdSHX0C4mjI+Nbdf7DbY5Z55Roo2nu0paJM81NeXysqqZpGZJx8JUXbaL2dofPkyT4fTwOk2cV09NV30Aq++gkZN8xjnx4tWq7QgsDyh/Phr9RUABXUwSWdcxPWwOXROyPISGRS5a1YNxKsVkR8CN1bw5PtfCLiMTpmW7gsVrTf5gULeaegS80GbQYddESetgWHAFbvSD5eCyxi0SIi7cdY2J4DbFIRmhecNEEODqtcwUGFFGlYuFoQX7nfQLbreg+wR8cxF9N8fFTHzkQeX2rhNc4/5ZzUWLhvyEoCKWVA/2kpNPTKDdc1J0M9Ml1PbxvFkRF4xy2JE3uVQVX3aJ3mqo23JpFdW+gApfJxPoewlqk12eWq7DVH/Tn9RzPR8NZckFD8QX9kSu4lRgsRcLyY/855u7Hb8pXR+Q8izp6/A83m/qoPUXBZDx0NjifBj7GI6lpH+lNkMX5Rc=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=cangr/mvsd-mongo-sync
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
